export const CREATE_NEW_GAME = 'CREATE_NEW_GAME';
export const COMPUTE_NEXT_TURN = 'COMPUTE_NEXT_TURN';
export const MARK_GAME_FINISHED = 'MARK_GAME_FINISHED';
export const ADD_TO_PLAYER_SCORE = 'ADD_TO_PLAYER_SCORE';
export const ANALYZE_BOARD_AND_SCORES = 'ANALYZE_BOARD_AND_SCORES';
